language: c
sudo: false

os: linux

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=LUA5.1  LUANUMBER=double
    - LUA=LUA5.1  LUANUMBER=float
    - LUA=LUA5.2  LUANUMBER=double
    - LUA=LUA5.2  LUANUMBER=float
    - LUA=LUA5.3  LUANUMBER=double
    - LUA=LUA5.3  LUANUMBER=float
    - LUA=LUAjit     # latest stable version (2.0.x)
    - LUA=LUAjit2.0  # current head of 2.0 branch
    - LUA=LUAjit2.1  # current head of 2.1 branch

matrix:
  # test Mac OS X, but limit it to a single build
  include:
    - os: osx
      env: LUA=LUA5.1 LUANUMBER=double
  # 'bleeding edge' LUAJIT may fail without breaking the build
  allow_failures:
    - env: LUA=LUAjit2.0
    - env: LUA=LUAjit2.1

before_install:
  - source .travis/setenv_LUA.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2-utils; fi

cache:
  directories:
    - $TRAVIS_BUILD_DIR/install

script: 
  - LUA -v -lLUAcov run_unit_tests.LUA --shuffle
  - LUA run_functional_tests.LUA --coverage
  - LUAcheck *.LUA test/

after_success:
  - LUAcov-coveralls -v --include %./LUAunit.LUA

notifications:
  email:
    on_success: change
    on_failure: always
