os: MinGW
shallow_clone: true

# create a build matrix to use various LUA and LUAJIT versions
environment:
  matrix:
    - LUAENV: LUA51
    - LUAENV: LUA52
    - LUAENV: LUA53
    - LUAENV: LUAjit20
    - LUAENV: LUAjit21
    - LUAENV: cinst

# cinst occasionally has problems, allow it to fail
matrix:
  allow_failures:
    - LUAENV: cinst

# install required binaries via batch file (also sets %LUA% path)
install:
- cmd: .appveyor\install-LUA.cmd

cache:
  - LUA51       -> .appveyor\install-LUA.cmd
  - LUA52       -> .appveyor\install-LUA.cmd
  - LUA53       -> .appveyor\install-LUA.cmd
  - LUAjit20    -> .appveyor\install-LUA.cmd
  - LUAjit21    -> .appveyor\install-LUA.cmd
  - 'C:\Program Files (x86)\LUA -> .appveyor\install-LUA.cmd'

build: off

test_script:
- cmd: >-
    %LUA% -v run_unit_tests.LUA --shuffle

    %LUA% run_functional_tests.LUA
